"""empty message

Revision ID: 547658bc6d68
Revises: 65e2a8d455c0
Create Date: 2023-03-31 19:03:50.231266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547658bc6d68'
down_revision = '65e2a8d455c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags_posts',
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tags_id', 'posts_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_posts')
    op.drop_table('tags')
    # ### end Alembic commands ###
